### PR TITLE
Set up cache for gradle and go 

### PR DESCRIPTION
**Pull request by mmorel-35**
The set up of caches reduce build time from 18 to 12 min.
This partially treats #688
I have also included dependabot for github-actions dependencies handling. It can also be activated for gradle if you are interested. 
Several gradle dependencies are also updated.

### CODE REVIEW

**Comment by Jeeppler** [comment]
@mmorel-35 thank you for your contribution.

**Review by Jeeppler — APPROVED** [review]
Looks good to me.

**Comment by Jeeppler** [comment]
@sven-dmlr and @de-jcup please have a look at this pull request.

**Comment by mmorel-35** [comment]
You're welcome @Jeeppler ,
With the new dependencies coming, you might have to upgrade to gradle 7.
Maybe the https://github.com/gradle/wrapper-validation-action will handle the installation instead of a direct download as I could see. Anyways some evolutions of the code are required for that upgrade, I have seen some warnings during the build.

**Comment by de-jcup** [comment]
Hello @mmorel-35 

Thank you very much for your PR. I would like to merge it -  but there is one little thing:

My company demands for every contributor to sign a CLA  (see https://github.com/Daimler/sechub/blob/develop/CONTRIBUTING.md#contributions )

To make it a little bit easier : 

1. Download CLA from https://github.com/Daimler/daimler-foss/blob/master/cla/2019-09-11_Daimler_FOSS_CLA_DaimlerTSS.pdf 
2. print it
3. sign it yourself
4. scan it or take a picture and email it to cla-tss@daimler.com


After this has been done I will be able to merge your PRs.

Hint: We are in the process to automate this and make more convenient for contributors in the near future.

**Review by sven-dmlr — APPROVED** [review]
Changes look good/plausible.

But I am NOT able to test the changes.

**Review by de-jcup — CHANGES_REQUESTED** [review]
As mentioned in my comments we need the accepted CLA. After this we are able to handle the PR.

**Comment by mmorel-35** [comment]
Hi @de-jcup , you should have it now. I just sent it.

**Review by de-jcup — APPROVED** [review]
@mmorel-35 : Thank you very much for your contribution - will be merged.

**Comment by de-jcup** [comment]
This PR closes #733 and does most of the things mentioned in #688 .

**Pull request merged**
